### PR TITLE
feat: add rate limit per minute

### PR DESCRIPTION
**Pull request by missuo**
- Allow limiting the number of requests per minute

### CODE REVIEW

**Comment by Geniucker** [comment]
Will routers other than `/v1/chat/completions` be influenced?

**Comment by missuo** [comment]
> Will routers other than `/v1/chat/completions` be influenced?

Now the **rate limit** only applies to `/v1/chat/completions`.

**Review by Geniucker — APPROVED** [review]

**Comment by missuo** [comment]
Because other PRs have been merged, conflicts exist. Do I need to deal with them?

**Review by aaamoon — APPROVED** [review]

**Comment by funnyzak** [comment]
> Because other PRs have been merged, conflicts exist. Do I need to deal with them?

Yes, conflicts need to be resolved.

**Pull request closed without merging**
