### PR TITLE
docs: add nginx reverse proxy configuration

### PR DESCRIPTION
**Pull request by missuo**

### CODE REVIEW

**Comment by Geniucker** [comment]
I think it not enouth to only reverse proxy `/v1`
image

**Comment by funnyzak** [comment]
I see the title `Use Nginx to support HTTPS`, but the description is for the nginx reverse proxy Copilot service, not for NGINX configuration of HTTPS.

**Comment by missuo** [comment]
> I see the title `Use Nginx to support HTTPS`, but the description is for the nginx reverse proxy Copilot service, not for NGINX configuration of HTTPS.

Setting up Nginx HTTPS is not as easy as Caddy, it involves applying for SSL certificates.

**Comment by missuo** [comment]
> I think it not enouth to only reverse proxy `/v1` image

I looked at the code, and I feel that the `/healthz` route seems unnecessary, its function is almost identical to the `/` root route.

Of course, my current reverse proxy cannot access `/`.

**Comment by funnyzak** [comment]
> > I think it not enouth to only reverse proxy `/v1` image
> 
> I looked at the code, and I feel that the `/healthz` route seems unnecessary, its function is almost identical to the `/` root route.
> 
> Of course, my current reverse proxy cannot access `/`.

I think /healthz can be used as a service status indicator.

**Comment by missuo** [comment]
> > > I think it not enouth to only reverse proxy `/v1` image
> > 
> > 
> > I looked at the code, and I feel that the `/healthz` route seems unnecessary, its function is almost identical to the `/` root route.
> > Of course, my current reverse proxy cannot access `/`.
> 
> I think /healthz can be used as a service status indicator.

For k8s? I noticed that [k8s has deprecated this endpoint](https://kubernetes.io/docs/reference/using-api/health-checks).

**Pull request closed without merging**
