### PR TITLE
fix: headers fit to the official extension

### LINKED ISSUE #183: Aligning the behaviour of official extensions
I think some of the detail in the code may increase the risk of banning.

https://github.com/aaamoon/copilot-gpt4-service/blob/65226a13b9eb571a3da06313bd3d29ec4b4c9f32/main.go#L87-L88

Here a different `Machineid` and `Sessionid` are created for each time, while the behaviour of the official extension is Machineid stays the same, and a new Sessionid is used when there is a new session. My exploring in the `extension.js` of the official extension confirms my idea. Also, the current implementation is missing some headers.

```js
// /home/codespace/.vscode-remote/extensions/github.copilot-chat-0.11.1/dist/extension.js
let a = t64.get(jt), l = { Authorization: hae.format("Bearer %s", r), "X-Request-Id": i, "X-GitHub-Api-Version": "2023-07-07", "VScode-SessionId": a.sessionId, "VScode-MachineId": a.machineId, ...a.getEditorVersionHeaders(), ...e.getExtraHeaders ? e.getExtraHeaders() : {} };
require("fs").writeFileSync("/tmp/copilot-headers.json",JSON.stringify(l));

// {"Authorization":"Bearer tid=xxx...","X-Request-Id":"cc8a3d0b-xxxx-xxxx-a3d6-0f4831ebc58f","X-GitHub-Api-Version":"2023-07-07","VScode-SessionId":"79180284-xxxx-423d-ad93-328528801acd1705243019488","VScode-MachineId":"99ddb858-xxxx-40cb-bd00-45a24ef59798","Editor-Version":"vscode/1.85.1","Editor-Plugin-Version":"copilot-chat/0.11.1","Openai-Organization":"github-copilot","Copilot-Integration-Id":"vscode-chat"}
// {"Authorization":"Bearer tid=xxx...","X-Request-Id":"3e4926ce-xxxx-xxxx-a4f2-829c2da8c9bc","X-GitHub-Api-Version":"2023-07-07","VScode-SessionId":"79180284-xxxx-423d-ad93-328528801acd1705243019488","VScode-MachineId":"99ddb858-xxxx-40cb-bd00-45a24ef59798","Editor-Version":"vscode/1.85.1","Editor-Plugin-Version":"copilot-chat/0.11.1","Openai-Organization":"github-copilot","Copilot-Integration-Id":"vscode-chat"}
```

While I haven't personally be blocked, I think we may need to make some fixes to align the behaviour of the official extensions.

### PR DESCRIPTION
**Pull request by kkocdko**
Fix #183

### CODE REVIEW

**Comment by Geniucker** [comment]
I've change the base branch to [aaamoon:fix-headers-fit-to-the-official-extension](https://github.com/aaamoon/copilot-gpt4-service/tree/fix-headers-fit-to-the-official-extension) and i'm gonna have more modification (mostly about caching machind id) on weekend. If anyone wants to do it before that, you can merge it now.

**Comment by funnyzak** [comment]
I have merged the code into the branch aaamoon:fix-headers-fit-to-the-official-extension, looking forward to your further optimization.

**Comment by Geniucker** [comment]
Hi @kkocdko , how did you know machineid is a UUID instead of a hexstring with length 64

**Comment by kkocdko** [comment]
@Geniucker see #183 , I modified the official extension to dump it's request headers.

**Comment by Geniucker** [comment]
> @Geniucker see #183 , I modified the official extension to dump it's request headers.

got it, thx for response

**Pull request merged**
